version: 2.1

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - test-dev:
          requires:
            - test
          context: org-global
          filters:
            branches:
              only:
                - rk
      - hold:
          type: approval
          requires:
            - test-dev
      - test-stage:
          requires:
            - test-dev
          filters:
            branches:
              only:
                - 2.1-orb-example
     

jobs:
  test-dev:
    docker:
      - image: cimg/node:15.3.0
    steps:
#       - checkout
#       - run:
#           name: Install Dependencies
#           command: npm install
      - run:
          name: Feteching Shared(context) variable
          command: echo $con_var
  test-stage:
    docker:
      - image: cimg/node:15.3.0
    steps:
#       - checkout
      - run:
          name: echo 
          command: echo 'This is test-stage'

  test:
    docker:
      - image: cimg/node:15.3.0
    steps:
#       - checkout
      # https://discuss.circleci.com/t/deploying-examples/8093
      - run:
          name: Branch - RK
          command: |
              if [ "${CIRCLE_BRANCH}" == "rk" ];
                then echo "This is from RK";
              fi
      - run:
          name: Branch - Master
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ];
                then echo "This is from master";
              fi
      
      
