version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

     

jobs:
  test:
    docker:
      - image: cimg/node:15.3.0
    steps:
      - checkout
      - run:
          name: Branch - RK
          command: |
              if [ "${CIRCLE_BRANCH}" == "rk" ];
                then echo "This is from RK";
              fi
      - run:
          name: Branch - Master
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ];
                then echo "This is from master";
              fi
      
      
#       - run:
#           name: Install Dependencies
#           command: npm install
#       - run:
#           name: Run Tests
#           command: npm run test
