version: 2.1

workflows:
  test-deploy:
    jobs:
      - test:
          filters:
            branches:
               only: rk
     

jobs:
  test:
    docker:
      - image: cimg/node:15.3.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
